<a href="https://colab.research.google.com/github/goldboy225/Code-Base-for-Research/blob/main/TON_IoT_Data_Understanding_using_ChatGPT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Load the data

In [6]:
# Import lib
import pandas as pd

# load the original dataset, which have not been processed by the authors
df = pd.read_csv('/content/drive/MyDrive/Datasets/TON-IoT/Train_Test_Network.csv')

In [7]:
# check the shape of the data
df.shape

(461043, 45)

In [8]:
# check the first 5 rows of the data
df.head()

,ts,src_ip,src_port,dst_ip,dst_port,proto,service,duration,src_bytes,dst_bytes,...,http_response_body_len,http_status_code,http_user_agent,http_orig_mime_types,http_resp_mime_types,weird_name,weird_addl,weird_notice,label,type
0,1554198358,3.122.49.24,1883,192.168.1.152,52976,tcp,-,80549.530260,1762852,41933215,...,0,0,-,-,-,bad_TCP_checksum,-,F,0,normal
1,1554198358,192.168.1.79,47260,192.168.1.255,15600,udp,-,0.000000,0,0,...,0,0,-,-,-,-,-,-,0,normal
2,1554198359,192.168.1.152,1880,192.168.1.152,51782,tcp,-,0.000000,0,0,...,0,0,-,-,-,bad_TCP_checksum,-,F,0,normal
3,1554198359,192.168.1.152,34296,192.168.1.152,10502,tcp,-,0.000000,0,0,...,0,0,-,-,-,-,-,-,0,normal
4,1554198362,192.168.1.152,46608,192.168.1.190,53,udp,dns,0.000549,0,298,...,0,0,-,-,-,bad_UDP_checksum,-,F,0,normal

In [9]:
# check the last 5 rows of the data
df.tail()

,ts,src_ip,src_port,dst_ip,dst_port,proto,service,duration,src_bytes,dst_bytes,...,http_response_body_len,http_status_code,http_user_agent,http_orig_mime_types,http_resp_mime_types,weird_name,weird_addl,weird_notice,label,type
461038,1556340862,192.168.1.32,33108,176.28.50.165,80,tcp,-,0.000000,0,0,...,0,0,-,-,-,-,-,-,1,xss
461039,1556423390,192.168.1.33,37242,34.230.157.88,443,tcp,-,0.000000,0,0,...,0,0,-,-,-,-,-,-,1,ransomware
461040,1556436603,192.168.1.37,4444,192.168.1.193,49178,tcp,-,290.371539,101568,2592,...,0,0,-,-,-,-,-,-,1,backdoor
461041,1556540442,192.168.1.31,60816,104.98.29.100,443,tcp,-,23.190902,32,31,...,0,0,-,-,-,-,-,-,1,mitm
461042,1556540442,192.168.1.31,41054,151.101.24.64,443,tcp,-,22.872314,32,31,...,0,0,-,-,-,-,-,-,1,mitm

In [10]:
# check the data types of the data
df.dtypes

ts                          int64
src_ip                     object
src_port                    int64
dst_ip                     object
dst_port                    int64
proto                      object
service                    object
duration                  float64
src_bytes                   int64
dst_bytes                   int64
conn_state                 object
missed_bytes                int64
src_pkts                    int64
src_ip_bytes                int64
dst_pkts                    int64
dst_ip_bytes                int64
dns_query                  object
dns_qclass                  int64
dns_qtype                   int64
dns_rcode                   int64
dns_AA                     object
dns_RD                     object
dns_RA                     object
dns_rejected               object
ssl_version                object
ssl_cipher                 object
ssl_resumed                object
ssl_established            object
ssl_subject                object
ssl_issuer                 object
http_trans_depth           object
http_method                object
http_uri                   object
http_version               object
http_request_body_len       int64
http_response_body_len      int64
http_status_code            int64
http_user_agent            object
http_orig_mime_types       object
http_resp_mime_types       object
weird_name                 object
weird_addl                 object
weird_notice               object
label                       int64
type                       object
dtype: object

In [11]:
# check the summary statistics of the data
df.describe()

,ts,src_port,dst_port,duration,src_bytes,dst_bytes,missed_bytes,src_pkts,src_ip_bytes,dst_pkts,dst_ip_bytes,dns_qclass,dns_qtype,dns_rcode,http_request_body_len,http_response_body_len,http_status_code,label
count,4.610430e+05,461043.000000,461043.000000,461043.000000,4.610430e+05,4.610430e+05,4.610430e+05,461043.000000,4.610430e+05,461043.000000,4.610430e+05,461043.000000,461043.000000,461043.000000,461043.000000,4.610430e+05,461043.000000,461043.000000
mean,1.555624e+09,39326.395095,7759.445861,8.473511,1.209926e+05,1.196931e+05,1.589523e+04,7.176183,1.820406e+03,8.331665,1.952803e+03,139.936088,5.630772,0.083721,0.028644,6.464905e+01,0.114529,0.349301
std,9.459234e+05,18469.455055,13943.625464,458.379390,1.157280e+07,1.219697e+07,3.560386e+06,517.942526,1.720414e+05,777.005922,1.605440e+05,2135.276314,27.690517,0.517138,6.222630,2.060057e+04,5.132271,0.476750
min,1.554198e+09,1.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000
25%,1.554294e+09,34296.000000,53.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.000000,4.000000e+01,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000
50%,1.556240e+09,43530.000000,136.000000,0.000036,0.000000e+00,0.000000e+00,0.000000e+00,1.000000,6.300000e+01,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000
75%,1.556327e+09,52724.500000,9197.000000,0.022757,5.500000e+01,2.500000e+02,0.000000e+00,2.000000,1.860000e+02,1.000000,3.530000e+02,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,1.000000
max,1.556549e+09,65534.000000,65530.000000,93516.929170,3.890855e+09,3.913853e+09,1.854527e+09,252181.000000,4.736725e+07,313943.000000,8.639552e+07,32769.000000,255.000000,5.000000,2338.000000,1.342438e+07,404.000000,1.000000

In [12]:
# check the number of missing values in each column
df.isnull().sum()

ts                        0
src_ip                    0
src_port                  0
dst_ip                    0
dst_port                  0
proto                     0
service                   0
duration                  0
src_bytes                 0
dst_bytes                 0
conn_state                0
missed_bytes              0
src_pkts                  0
src_ip_bytes              0
dst_pkts                  0
dst_ip_bytes              0
dns_query                 0
dns_qclass                0
dns_qtype                 0
dns_rcode                 0
dns_AA                    0
dns_RD                    0
dns_RA                    0
dns_rejected              0
ssl_version               0
ssl_cipher                0
ssl_resumed               0
ssl_established           0
ssl_subject               0
ssl_issuer                0
http_trans_depth          0
http_method               0
http_uri                  0
http_version              0
http_request_body_len     0
http_response_body_len    0
http_status_code          0
http_user_agent           0
http_orig_mime_types      0
http_resp_mime_types      0
weird_name                0
weird_addl                0
weird_notice              0
label                     0
type                      0
dtype: int64

In [13]:
# check the number of unique values in each column
df.nunique()

ts                        115666
src_ip                     11536
src_port                   53671
dst_ip                      5268
dst_port                    2666
proto                          3
service                       10
duration                  124727
src_bytes                   3056
dst_bytes                   3511
conn_state                    13
missed_bytes                 929
src_pkts                     414
src_ip_bytes                4549
dst_pkts                     332
dst_ip_bytes                4577
dns_query                  14149
dns_qclass                     3
dns_qtype                     12
dns_rcode                      5
dns_AA                         3
dns_RD                         3
dns_RA                         3
dns_rejected                   3
ssl_version                    4
ssl_cipher                     6
ssl_resumed                    3
ssl_established                3
ssl_subject                    6
ssl_issuer                     5
http_trans_depth              11
http_method                    4
http_uri                      74
http_version                   2
http_request_body_len          6
http_response_body_len        68
http_status_code               8
http_user_agent               36
http_orig_mime_types           3
http_resp_mime_types          10
weird_name                    12
weird_addl                     4
weird_notice                   2
label                          2
type                          10
dtype: int64